version: '3.2'

services:

  site-nginx:
    image: nginx:latest
    links:
      - site-php
    ports:
      - "8080:80"
    volumes:
      - ./site/site.conf:/etc/nginx/conf.d/default.conf
      - ./site/src:/var/www/site/
    networks:
      net:
        ipv4_address: 172.28.1.1

  site-php:
    image: phalconphp/php-fpm:7-min
    volumes:
        - ./site/src:/var/www/site/
    networks:
      net:
        ipv4_address: 172.28.1.2

  users-nginx:
    image: nginx:latest
    links:
      - users-php
    volumes:
      - ./users/users.conf:/etc/nginx/conf.d/default.conf
      - ./users/src:/var/www/users/
    networks:
      net:
        ipv4_address: 172.28.1.3

  users-php:
    image: phalconphp/php-fpm:7-min
    volumes:
        - ./users/src:/var/www/users/
    networks:
      net:
        ipv4_address: 172.28.1.4
    entrypoint: bash -c 'apt-get -y update && apt-get install -y sqlite3 libsqlite3-dev && rm -f /var/www/users/database/sqlite.db && sqlite3 /var/www/users/database/sqlite.db "" && cd /var/www/users/ && php vendor/bin/phinx migrate && php vendor/bin/phinx seed:run && php-fpm -F'
    tty: true
  
networks:
  net:
    ipam:
      config:
        - subnet: 172.28.0.0/16